const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const path = require('path');
const nodes = new Map();
const node = selector => {
  if (!nodes.has(selector)) nodes.set(selector, {value: selector === '#habit-filter' ? 'active' : '', textContent:'', innerHTML:'', querySelectorAll:()=>[], reset(){}, classList:{contains:()=>false}});
  return nodes.get(selector);
};
let token='alice', response=async()=>({ok:true,json:async()=>({data:[]})});
const context={document:{querySelector:node},localStorage:{getItem:()=>token},AbortController,setTimeout,clearTimeout,fetch:(...args)=>response(...args),window:{}};
vm.createContext(context);
const source=fs.readFileSync(path.join(__dirname,'../internal/httpapi/assets/habits.js'),'utf8');
vm.runInContext(source.replace('  bind();','  window.test = {state,monthCells,render,load,check,reset};'),context);
const api=context.window.test;
const h={id:'a',title:'<img onerror=alert(1)>',description:'safe',icon:'read',archived:false,time_zone:'UTC',today:'2024-02-20',start_date:'2024-02-10',checkins:['2024-02-19'],total:1,current_streak:1,longest_streak:1};
(async()=>{
 api.state.items=[h];api.state.loaded=true;api.state.month='2024-02';api.render();
 assert(node('#habit-list').innerHTML.includes('&lt;img'));
 assert(!node('#habit-list').innerHTML.includes('<img'));
 let html=api.monthCells(h,'2024-02');
 assert.equal((html.match(/data-habit-date=/g)||[]).length,29);
 assert(/data-habit-date="2024-02-21"[^>]*disabled/.test(html));
 assert(/data-habit-date="2024-02-09"[^>]*disabled/.test(html));
 assert(!/data-habit-date="2024-02-20"[^>]*disabled/.test(html));
 assert.equal((api.monthCells({...h,archived:true},'2024-02').match(/ disabled/g)||[]).length,29);
 response=async()=>({ok:false,status:500,json:async()=>({error:{message:'failure'}})});
 await api.check('a',h.today,true);
 assert.equal(api.state.items[0].checkins.length,1);
 assert.equal(node('#habit-status').textContent,'failure');assert.equal(api.state.busy,false);
 let release;response=()=>new Promise(resolve=>{release=resolve;});
 const pending=api.load();api.reset();token='bob';
 release({ok:true,json:async()=>({data:[h]})});await pending;
 assert.equal(api.state.items.length,0);assert.equal(api.state.loaded,false);
 response=async()=>({ok:true,json:async()=>({data:[]})});await api.load();
 assert.equal(api.state.loaded,true);
 const index=fs.readFileSync(path.join(__dirname,'../internal/httpapi/assets/index.html'),'utf8');
 for(const selector of nodes.keys()) assert(index.includes(`id="${selector.slice(1)}"`),`Missing ${selector}`);
 console.log('Habits UI smoke passed: calendar, escaping, failure recovery, account isolation, DOM wiring.');
})().catch(error=>{console.error(error);process.exitCode=1;});
